apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: clusters/cluster1
    repoURL: https://github.com/smarunich/gitops.git
    targetRevision: HEAD