apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bookinfo
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev-bookinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: dev-bookinfo
    repoURL: https://github.com/smarunich/gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
